### ISSUE TITLE
sbt-web-scalajs

### ISSUE THREAD

**Issue by antonkulaga** [vmunier/sbt-web-scalajs#10]
Actually, I do not see any play-specific things here, maybe it can be renamed to just sbt-web-scalajs, as it seems to be usable in both play and akka-http projects.

**Comment by vmunier** [comment]
Indeed, there is no play-specific things anymore. I will consider renaming it to sbt-web-scalajs or sbtweb-scalajs. Users of the plugin would have to edit their plugins.sbt file and I would have to update the various places where links to sbt-play-scalajs have been posted (Scala.js website, the sbt plugins page, etc.).

I would be interested in seing an akka-http project using sbt-play-scalajs and get feedback to know whether the plugin is really useful outside of a play project.

**Comment by antonkulaga** [comment]
I've got some problems with it. To make sbtweb pack its files to the jar I add following line there
```scala
	(managedClasspath in Runtime) += (packageBin in Assets).value
```
But If I have enabled Sbt-play plugin it freezes my website when I try to open it. 
Here is an example of my configuration
```scala
lazy val preview = crossProject
		.crossType(CrossType.Full)
		.in(file("preview"))
		.settings(commonSettings++publishSettings: _*)
		.settings(
			name := "preview"
		)
		.jsConfigure(p=>p.dependsOn(facade).enablePlugins(ScalaJSPlay))
		.jsSettings(
			libraryDependencies ++= Dependencies.sjsLibs.value,
			persistLauncher in Compile := true,
			persistLauncher in Test := false,
			jsDependencies += RuntimeDOM % "test"
		)
		.jvmConfigure(p=>p.enablePlugins(SbtTwirl,SbtWeb).enablePlugins(PlayScalaJS)) //despite "Play" in name it is actually sbtweb-related plugin
		.jvmSettings(Revolver.settings:_*)
		.jvmSettings(
			libraryDependencies ++= Dependencies.akka.value ++ Dependencies.webjars.value,
			mainClass in Compile :=Some("org.denigma.preview.Main"),
			mainClass in Revolver.reStart := Some("org.denigma.preview.Main")
		)

	lazy val previewJS = preview.js
	lazy val previewJVM = preview.jvm settings( 
		scalaJSProjects := Seq(preview.js),
		pipelineStages := Seq(scalaJSProd,gzip),
		(managedClasspath in Runtime) += (packageBin in Assets).value /*this freezes my whole build*/
		)

```

**Comment by antonkulaga** [comment]
>I would be interested in seing an akka-http project using sbt-play-scalajs and get feedback to know whether the plugin is really useful outside of a play project.

I've used it for preview project in my codemirror facade, see https://github.com/antonkulaga/codemirror-facade/blob/master/project/Build.scala

The main problem is that while scalaJSProd is Pipeline.Stage scalaJSDev and  is not. So, I had to create a pipeline stage for it.

**Comment by joprice** [comment]
It would be nice to at least note in the readme that it's possible to use this without Play. I just integrated it into an akka-http project with no issues, but not until after I stumbled upon this issue from a comment in antonkulaga's code.

**Comment by vmunier** [comment]
Hi, I agree it would be nice to let people know that it's possible to use the plugin outside of a Play application.
I am curious to see how the integration between sbt-play-scalajs and akka-http works. For instance, is it possible in akka-http to know whether the application runs in Dev or Prod mode? Do you have your akka-http project available somewhere?

**Comment by antonkulaga** [comment]
Yes, I use akka-http in most of my opensource projects. For instance it is used https://github.com/antonkulaga/scala-js-binding to provide previews. Right now I have an issue with source maps, other parts work well

**Comment by vmunier** [comment]
More than a year later, the project has finally been renamed to `sbt-web-scalajs`. Usage has changed, you can take a look at the [release note](https://github.com/vmunier/sbt-web-scalajs/releases/tag/v1.0.0) or one of the two examples to help you migrating from sbt-play-scalajs v0.3.1 to sbt-web-scalajs v1.0.0.
- [Play with Scala.js app](https://github.com/vmunier/play-with-scalajs-example)
- [Akka HTTP with Scala.js app](https://github.com/vmunier/akka-http-with-scalajs-example)
