### ISSUE TITLE
Scala 3 compatibility

### ISSUE THREAD

**Issue by TimoMeijer** [vmunier/sbt-web-scalajs#105]
In Scala 3 the sourceMap compiler option has been changed from `-P:scalajs:mapSourceURI:` to `-scalajs-mapSourceURI:`, which means that the current version of the plugin is incompatible with Scala 3.

**Comment by vmunier** [comment]
sbt-web-scalajs `v1.2.0` has been released and is compatible with Scala 3.

Commits adding Scala 3 support: https://github.com/vmunier/sbt-web-scalajs/commit/8b65c56faa6bc4b24ee79adf7eb6be07ba8d25d4, https://github.com/vmunier/sbt-web-scalajs/commit/a7a4b2bf84df9692d05031451f637ded4c0aa08c.
