### ISSUE TITLE
spray IO

### ISSUE THREAD

**Issue by elyphas** [vmunier/sbt-web-scalajs#19]
Is possible to do works it, "sbt-play-scalajs" with spray?, if so, someone could tell me,  how can I do that?, I get only Tutorial.scala  in the browser, but is empty, :)

**Comment by antonkulaga** [comment]
I used it with akka-http and it worked well. I think akka-http configuration is similar to spray one

**Comment by vmunier** [comment]
Hi, I'd recommend to migrate from Spray to Akka HTTP, this [documentation page](http://doc.akka.io/docs/akka/2.4.7/scala/http/migration-from-spray.html) can help you with that.

There is also an example showing how you can integrate Akka HTTP with Scala.js: https://github.com/vmunier/akka-http-with-scalajs-example

If you prefer to keep using Spray, then you can follow the [README.md](https://github.com/vmunier/sbt-web-scalajs/blob/bec5b5ac43dae1efac75843cd98a719767249ad4/README.md) to set it up, but there is no available example that I know of.
