### ISSUE TITLE
devCommands is too strict

### ISSUE THREAD

**Issue by julienrf** [vmunier/sbt-web-scalajs#27]
If I use `server/run` (instead of, say, `;project server; run`) the command is not recognized as a “dev” command. Same with `re-start`.

**Comment by julienrf** [comment]
A solution would be to test like this:

~~~ scala
(devCommands in scalaJSPipeline).value.exists(userCommand endsWith _)
~~~

**Comment by vmunier** [comment]
Good catch! Testing the suffix with `endsWith` could also match other tasks by mistake (e.g. `myrun`). I'll keep the characters after the last `/` instead, something like:
```
val userCommand = state.value.history.current.takeWhile(c => !c.isWhitespace).split('/').last
(devCommands in scalaJSPipeline).value.contains(userCommand)
```

**Comment by sjrd** [comment]
What about `compile:run`, then? There's also the syntax `compile::run` (which means something different. You should split by either `/`, `:` or `::` to get something meaningful that way.

**Comment by vmunier** [comment]
That's true, there are more cases to handle; `.split(Array('/', ':')).last` would work. Here's the fully-qualified reference to a setting or task `{<build-uri>}<project-id>/config:intask::key` from the sbt [documentation](http://www.scala-sbt.org/0.13/docs/Inspecting-Settings.html).
