### ISSUE TITLE
Have client-opt.js and client-launcher.js in the same file. One request less means a lot.

### ISSUE THREAD

**Issue by strelec** [vmunier/sbt-web-scalajs#35]
Why are those two files separate in the first place?

**Comment by vmunier** [comment]
Hello, what versions of Scala.js and sbt-web-scalajs are you using?
The `-launcher.js` file is not generated anymore when using Scala.js `v0.6.15` along with sbt-web-scalajs `v1.0.4`; the `-fastopt.js` and `-opt.js` files now include the call to the main method.

**Comment by strelec** [comment]
Thanks, I really just needed to upgrade to 1.0.4.
