### ISSUE TITLE
Publish for sbt 1.0.0-RC2?

### ISSUE THREAD

**Issue by ngbinh** [vmunier/sbt-web-scalajs#37]
sbt-1.0.0-RC2 was released yesterday http://www.scala-sbt.org/1.0/docs/sbt-1.0-Release-Notes.html#sbt+1.0.0-RC2

**Comment by vmunier** [comment]
Hi,
sbt-web-scalajs depends on sbt-web and Scala.js, which need to be published for SBT v1.0.0-RC2 first before we can upgrade this plugin.

**Comment by ngbinh** [comment]
Yes. tracking issues here https://github.com/scala-native/sbt-crossproject/issues/48

**Comment by ngbinh** [comment]
https://github.com/sbt/sbt-web/issues/141

**Comment by nafg** [comment]
1.0.0 was released...

**Comment by joan38** [comment]
This can be closed by https://github.com/vmunier/sbt-web-scalajs/pull/38

**Comment by ngbinh** [comment]
thanks, closing!
