### ISSUE TITLE
Specify opt js output file name

### ISSUE THREAD

**Issue by richbirch** [vmunier/sbt-web-scalajs#41]
I'm trying to make sure we don't have browsers caching our JS when we deploy a new version of the app. We're using scalajs-bundler.

Is there an option somewhere to specify the final optimised js file name, ie rather than [projectname]-opt-bundle.js or [projectname]-fastopt-bundle.js

I'm struggling to find which plugin is responsible for this so please forgive me if I'm asking in the wrong place.

Thanks

**Comment by vmunier** [comment]
Hi,

I would suggest looking at sbt-digest https://github.com/sbt/sbt-digest, which prepends the file name with a hash, the hash is computed from the content of the file. I.e.: the file name changes when the content of the file changes. So, your optimised JS file name would look like `ac581be5ed737bd378ef71d57190117b-client-opt.js`.

Here's an example that runs with a Play HTTP server and uses the sbt-digest plugin:
```
$ sbt new vmunier/play-scalajs.g8 --name=play-scalajs --organization=com.example
$ cd play-scalajs
$ sbt "start -Dplay.http.secret.key='tmpsecretkey'"
$ open http://localhost:9000
# In your web page, right click to see the source, you should see a hash prepended to `-client-opt.js`
```

**Comment by richbirch** [comment]
Thanks very much for the quick reply mate. I'll certainly give that a try

**Comment by richbirch** [comment]
I think scalajs-bundler might be trampling on sbt-digest in our project as I'm not able to get the same behaviour as in your example above. I'll try asking over there and see what suggestions they have.

Thanks for the help
