### ISSUE TITLE
error: not found: value devCommands

### ISSUE THREAD

**Issue by Fraer** [vmunier/sbt-web-scalajs#88]
After updating from v1.0.11-0.6 to v1.1.0-0.6 we have the following error:

```
build.sbt:234: error: not found: value devCommands
    devCommands in scalaJSPipeline ++= Seq("test", "testOnly", "doc", "~run", "~reStart"),
    ^
[error] sbt.compiler.EvalException: Type error in expression
```

There is no more devCommands ?

**Comment by vmunier** [comment]
That's correct, `devCommands` has been removed in sbt-web-scalajs `v1.1.x`. You now need to set `scalaJSStage` to run `fastOptJS` or `fullOptJS`. 

Please have a look at the sbt-web-scalajs v1.1.0 release https://github.com/vmunier/sbt-web-scalajs/releases/tag/v1.1.0, which details the breaking changes introduced in v1.1.0
